#socks5代理配置
socks:
  dstAddr:
    #不代理名单(firefox一堆自带请求浪费流量)
    dropList:
      - firefox.com
      - deepl.com
      - rapidssl.com
      - firefoxchina.cn
      - lencr.org
      - mozilla.org
      - mozilla.com
      - mozilla.net
      - pki.goog
      - adblockplus.dev
  #配置websocket服务地址
  ws:
#    server: ws://localhost:18082/ws
